# Generated by Django 4.2.4 on 2024-02-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor',
            new_name='doctor',
        ),
    ]
